services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: acme_13_user
      POSTGRES_PASSWORD: acme_13_password
      POSTGRES_DB: acme_13_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
